### ISSUE TITLE
Please delete expired branches

### ISSUE THREAD

**Issue by young1ll** [TubePlus/TubePlusFront#10]
- 아래 브랜치들을 확인하고 만료된 브랜치들은 삭제해주세요. @onmer99

### Branches
- `main`: 최종 배포판
- `develop`: 개발용 배포판
- `boilerplate`: tubePlus 보일러플레이트(라이브러리 등)
- `community`: ?
- `dev`: ?
- `mainpage`: ?
- `settings`: ?

**Comment by onmer99** [comment]
확인했습니다. 다음 PR 날릴때 반영하여 dev를 제외한 한 브런치에서 올리고 반영이 되면 삭제하겠습니다.
